# Generated by Django 5.1.2 on 2024-10-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student1",
            fields=[
                ("name", models.CharField(max_length=50)),
                ("rollno", models.IntegerField(primary_key=True, serialize=False)),
                ("maths", models.FloatField()),
                ("chemistry", models.FloatField()),
                ("physics", models.FloatField()),
                ("total_marks", models.FloatField()),
                ("percentage", models.FloatField()),
                ("classteacher", models.CharField(max_length=50)),
            ],
        ),
    ]
