# Generated by Django 5.1.2 on 2024-10-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App2", "0005_student1_classteacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student1",
            name="classteacher",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
