# Generated by Django 5.1.2 on 2024-10-22 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App2", "0006_alter_student1_classteacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student1",
            name="teacher_id",
        ),
        migrations.DeleteModel(
            name="Teacher",
        ),
    ]
