# Generated by Django 5.1.2 on 2024-10-22 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App2", "0007_remove_student1_teacher_id_delete_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("name", models.CharField(max_length=50)),
                ("emp_id", models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name="student1",
            name="teacher_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="App2.teacher",
            ),
        ),
    ]
