# Generated by Django 5.1.2 on 2024-10-22 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App2", "0008_teacher_student1_teacher_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student1",
            name="classteacher",
        ),
    ]
