# Generated by Django 5.1.2 on 2024-10-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App2", "0009_remove_student1_classteacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="performance",
            field=models.FloatField(default=0),
        ),
    ]
