# Generated by Django 5.1.2 on 2024-10-23 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App2", "0012_alter_student1_teacher_id"),
        ("app_School", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="school_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app_School.school",
            ),
        ),
    ]
