# Generated by Django 5.1.2 on 2024-10-23 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App2", "0013_teacher_school_id"),
        ("app_Department", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="school_id",
            new_name="sc_id",
        ),
        migrations.AddField(
            model_name="teacher",
            name="dept_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app_Department.department",
            ),
        ),
    ]
