# Generated by Django 5.1.2 on 2024-10-24 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App2", "0014_rename_school_id_teacher_sc_id_teacher_dept_id"),
        ("app_Department", "0001_initial"),
        ("app_School", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student1",
            name="dept_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app_Department.department",
            ),
        ),
        migrations.AddField(
            model_name="student1",
            name="sc_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app_School.school",
            ),
        ),
    ]
