# Generated by Django 5.1.2 on 2024-10-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App2", "0017_remove_teacher_hod_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="hod_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
