# Generated by Django 5.1.2 on 2024-10-24 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App2", "0018_teacher_hod_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="hod_name",
        ),
    ]
