# Generated by Django 5.1.2 on 2024-10-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App2", "0022_alter_student1_rollno"),
    ]

    operations = [
        migrations.AddField(
            model_name="student1",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
