# Generated by Django 5.1.2 on 2024-10-28 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App2", "0023_student1_is_active"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Teacher",
        ),
    ]
