# Generated by Django 5.1.2 on 2024-11-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App2", "0024_delete_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student1",
            name="chemistry",
        ),
        migrations.RemoveField(
            model_name="student1",
            name="maths",
        ),
        migrations.RemoveField(
            model_name="student1",
            name="physics",
        ),
        migrations.AlterField(
            model_name="student1",
            name="percentage",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="student1",
            name="total_marks",
            field=models.FloatField(),
        ),
    ]
