# Generated by Django 5.1.2 on 2024-11-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_User", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(max_length=100),
        ),
    ]
