# Generated by Django 5.1.2 on 2024-11-04 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_User", "0002_alter_users_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="username",
        ),
    ]
