# Generated by Django 5.1.2 on 2024-11-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_User", "0003_remove_users_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="username",
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
