# Generated by Django 5.1.2 on 2024-11-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_Department", "0014_remove_departments_sc_id"),
        ("app_User", "0006_users_department_users_first_name_users_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="department",
            field=models.ManyToManyField(
                related_name="user_tea", to="app_Department.departments"
            ),
        ),
    ]
