# Generated by Django 5.1.2 on 2024-11-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_Department", "0016_rename_departmentss_departments"),
        ("app_User", "0007_alter_users_department_alter_users_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="users",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="users",
            name="department",
            field=models.ManyToManyField(blank=True, to="app_Department.departments"),
        ),
        migrations.AlterField(
            model_name="users",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
