# Generated by Django 5.1.2 on 2024-10-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="Roll_no",
            field=models.IntegerField(default=0),
        ),
    ]
