# Generated by Django 5.1.2 on 2024-10-24 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_School", "0002_school_created_on_school_dept_id_school_updated_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="school",
            name="dept_id",
        ),
    ]
