# Generated by Django 5.1.2 on 2024-10-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_School", "0004_alter_school_sc_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
