# Generated by Django 5.1.2 on 2024-10-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_Department", "0011_alter_departments_sc_id"),
        ("app_School", "0005_school_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="departments",
            field=models.ManyToManyField(
                related_name="departments", to="app_Department.departments"
            ),
        ),
    ]
