# Generated by Django 5.1.2 on 2024-10-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_Department", "0011_alter_departments_sc_id"),
        ("app_School", "0007_alter_school_departments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="departments",
            field=models.ManyToManyField(
                related_name="school_departments_list", to="app_Department.departments"
            ),
        ),
    ]
