# Generated by Django 5.1.2 on 2024-10-25 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_Department", "0008_alter_departments_dept_id"),
        ("app_School", "0004_alter_school_sc_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher2",
            fields=[
                ("name", models.CharField(max_length=50)),
                ("emp_id", models.AutoField(primary_key=True, serialize=False)),
                ("performance", models.FloatField(default=0)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "dept_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app_Department.departments",
                    ),
                ),
                (
                    "sc_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app_School.school",
                    ),
                ),
            ],
        ),
    ]
