# Generated by Django 5.1.2 on 2024-10-23 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_School", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("hod_name", models.CharField(max_length=100)),
                ("dept_name", models.CharField(max_length=100)),
                ("dept_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "sc_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app_School.school",
                    ),
                ),
            ],
        ),
    ]
