# Generated by Django 5.1.2 on 2024-10-24 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_Department", "0002_department_created_on_department_updated_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="emp_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app_Department.department",
            ),
        ),
    ]
