# Generated by Django 5.1.2 on 2024-10-24 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App2", "0019_remove_teacher_hod_name"),
        ("app_Department", "0005_remove_department_emp_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="hod_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="App2.teacher",
            ),
        ),
    ]
