# Generated by Django 5.1.2 on 2024-10-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App2", "0019_remove_teacher_hod_name"),
        ("app_Department", "0006_alter_department_hod_name"),
        ("app_School", "0003_remove_school_dept_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Department",
            new_name="Departments",
        ),
    ]
