# Generated by Django 5.1.2 on 2024-10-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_Department", "0007_rename_department_departments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departments",
            name="dept_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
