# Generated by Django 5.1.2 on 2024-10-25 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_Department", "0008_alter_departments_dept_id"),
        ("app_Teacher", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departments",
            name="hod_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="app_Teacher.teacher2",
            ),
        ),
    ]
