# Generated by Django 5.1.2 on 2024-10-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_Department", "0009_alter_departments_hod_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="departments",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
