# Generated by Django 5.1.2 on 2024-11-01 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_Department", "0012_remove_departments_sc_id"),
        ("app_School", "0008_alter_school_departments"),
    ]

    operations = [
        migrations.AddField(
            model_name="departments",
            name="sc_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="school_departments",
                to="app_School.school",
            ),
        ),
    ]
