# Generated by Django 5.1.2 on 2024-11-02 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_Department", "0013_departments_sc_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="departments",
            name="sc_id",
        ),
    ]
