# Generated by Django 5.1.2 on 2024-11-06 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App2", "0025_remove_student1_chemistry_remove_student1_maths_and_more"),
        ("app_Department", "0015_rename_departments_departmentss"),
        ("app_School", "0009_rename_school_schools"),
        ("app_Teacher", "0004_remove_teacher2_dept_id"),
        ("app_User", "0006_users_department_users_first_name_users_last_name_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Departmentss",
            new_name="Departments",
        ),
    ]
